name: Deploy AWS RDS PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.7

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-2
        aws configure set output json

    - name: Initialize Terraform
      run: terraform init

    - name: Deploy RDS
      run: terraform apply -auto-approve

    - name: Capture Outputs
      id: outputs
      run: echo "::set-output name=rds_endpoint::$(terraform output -raw rds_endpoint)"

    - name: Store RDS Endpoint as Environment Variable
      run: |
        echo "RDS_ENDPOINT=${{ steps.outputs.outputs }}" >> $GITHUB_ENV

    - name: Cleanup
      run: terraform destroy -auto-approve

